version: "3"

services:
  db:
    image: registry1.dso.mil/ironbank/opensource/mariadb/mariadb:10.9.4
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./db.env

  app:
    image: registry1.dso.mil/ironbank/matomo-org/matomo:4.13.0
    restart: always
    links:
      - db
    volumes:
      # - ./config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env
    depends_on:
      - db

  web:
    image: registry1.dso.mil/ironbank/opensource/nginx/nginx:1.20.0
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

volumes:
  db:
  matomo:
